server:
  host: 0.0.0.0
  port: 8004
  use_ngrok: false
  use_auth: false
  auth_username: user
  auth_password: password
  log_file_path: logs\tts_server.log
  log_file_max_size_mb: 10
  log_file_backup_count: 5
model:
  repo_id: ResembleAI/chatterbox
tts_engine:
  device: cuda
  predefined_voices_path: voices
  reference_audio_path: reference_audio
  default_voice_id: Emily.wav
paths:
  model_cache: model_cache
  output: outputs
generation_defaults:
  temperature: 0.8
  exaggeration: 0.5
  cfg_weight: 0.5
  seed: 0
  speed_factor: 1.0
  language: en
audio_output:
  format: wav
  sample_rate: 24000
  max_reference_duration_sec: 30
ui_state:
  last_text: "It was the best of times, it was the worst of times, it was the age\
    \ of wisdom, it was the age of foolishness, it was the epoch of belief, it was\
    \ the epoch of incredulity, it was the season of Light, it was the season of Darkness,\
    \ it was the spring of hope, it was the winter of despair, we had everything before\
    \ us, we had nothing before us, we were all going direct to Heaven, we were all\
    \ going direct the other way \u2013 in short, the period was so far like the present\
    \ period, that some of its noisiest authorities insisted on its being received,\
    \ for good or for evil, in the superlative degree of comparison only.\nThere were\
    \ a king with a large jaw and a queen with a plain face, on the throne of England;\
    \ there were a king with a large jaw and a queen with a fair face, on the throne\
    \ of France. In both countries it was clearer than crystal to the lords of the\
    \ State preserves of loaves and fishes, that things in general were settled for\
    \ ever.\nIt was the year of Our Lord one thousand seven hundred and seventy-five.\
    \ Spiritual revelations were conceded to England at that favoured period, as at\
    \ this. Mrs. Southcott had recently attained her five-and-twentieth blessed birthday,\
    \ of whom a prophetic private in the Life Guards had heralded the sublime appearance\
    \ by announcing that arrangements were made for the swallowing up of London and\
    \ Westminster. Even the Cock-lane ghost had been laid only a round dozen of years,\
    \ after rapping out its messages, as the spirits of this year last past (supernaturally\
    \ deficient in originality) rapped out theirs.\n"
  last_voice_mode: clone
  last_predefined_voice: Emily.wav
  last_reference_file: Tighnari Voice Generator.mp3
  last_seed: 1775
  last_chunk_size: 240
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: false
  theme: dark
ui:
  title: Chatterbox TTS Server
  show_language_select: true
  max_predefined_voices_in_dropdown: 50
debug:
  save_intermediate_audio: false
